### ISSUE TITLE
Feature Request: Whitelist all tools?

### ISSUE THREAD

**Issue by KeksXtreme** [Elemend/Vein-Miner-Version-2#2]
Why would you artificially restrict which tools can be used and which cannot...?

**Comment by Elemend** [comment]
This may seem artificial, but it was my design choice from the very start of me working on this. I wanted the player be able to advance in the Vanilla Game first. Coincidentally, another argument is the Durability System. I don't have a way to prevent veinmining if the durability is too low. Now Imagine veinmining with wood tools. It would just be stupid; you could mine thousands of blocks for no cost at all. Me making it work with iron tools is already the most accomodation I can do.
