### ISSUE TITLE
Prevent the destruction of the tools

### ISSUE THREAD

**Issue by lipki** [Elemend/Vein-Miner-Version-2#5]
An option for the blocks destruction to stop just before the tool is destroyed, to allow repair.
It is difficult to gauge if the tool will be destroyed, so this option would save tools.

**Comment by Elemend** [comment]
I think I found a way to track the durability while the Blocks are being mined. Which in turn means I can stop the Blocks from being mined in the first place. A Drawback to this would be that the cubic shape in which Blocks are being mined would be lost. It would take a more chaotic pattern. I guess that is okay?

**Comment by lipki** [comment]
Yes, it would be perfect, it is better to lose the cubic form, than the tool :)

**Comment by Elemend** [comment]
Well it's been some time...  I uploaded a 1.14 Version(18w50a) that has this functionality built in. I plan on bringing these changes back to the 1.13 Version, but that will take some more time to finish. So for now you can try the 1.14 Version at least.

**Comment by Elemend** [comment]
I chose to publish this as a seperate new Version.
